### ISSUE TITLE
CMS specific extensions

### ISSUE THREAD

**Issue by laryn** [civicrm/civicrm-backdrop#101]
The Extensions page lists a link for Backdrop-specific extensions:

> You may also want to check the directory for native Backdrop modules that may be useful for you (CMS-specific modules are not listed here).

When clicked, however, it's a 404:

- https://civicrm.org/extensions/Backdrop

**Comment by seamuslee001** [comment]
ping @totten @mlutfy this feels more website than anything else e.g. https://civicrm.org/extensions/Drupal works and https://civicrm.org/extensions/WordPress works but not Perhpas another view page needs to be configured

**Comment by mlutfy** [comment]
https://lab.civicrm.org/marketing/civicrm-website/issues/161#note_26511

**Comment by seamuslee001** [comment]
@laryn it should be sorted now

**Comment by laryn** [comment]
@seamuslee001 Thank you! Now to start getting a few modules listed in there...
