### ISSUE TITLE
Idea: a Layouts visibility condition for CiviCRM checksum

### ISSUE THREAD

**Issue by laryn** [civicrm/civicrm-backdrop#124]
I was just working on something where we send out a checksum link to a private webform, and I was trying to add a block for anonymous users (e.g. "Check your email for the special link") but came to realize even when they click the special link, they will still be anonymous users. Perhaps there's a way to create a CiviCRM-specific visibility condition for Layouts to make sure a valid checksum is in use.

**Comment by laryn** [comment]
@herbdool I'm thinking of taking a crack at this. Do you agree this module would be a good place for it rather than a separate module?

**Comment by herbdool** [comment]
Can't hurt to try add it here first. It can always be spun off if it's not considered to be widely useful.

**Comment by laryn** [comment]
@herbdool @MegaphoneJon Ready for testing...

**Comment by herbdool** [comment]
What's an easy way to test?

**Comment by laryn** [comment]
For testing, here's what I did (on a dev site):

- Create a Custom block on the home page that just says "SHOW THIS BLOCK" or something.
- Test the "negate" versions of the visibility rule one at a time easily (Change the setting to Invalid checksum; then Invalid checksum AND logged out and test those conditions)
- Change the setting again to the "Valid checksum OR logged in" rule and test the logged in condition
- Funnel emails from the site into a mail log file (`define( 'CIVICRM_MAIL_LOG',...` in `civicrm.settings.php`)
- Send an email with a link to the homepage and a link such as `https://example.com/?cid={contact.contact_id}&{contact.checksum}` in the body
- Get the generated URL from the mail log and paste into the browser in a private window to test the "Valid checksum OR logged in" rule again
- Change the visibility rule to "Valid checksum" and test the checksum link again in private window

**Comment by herbdool** [comment]
If tested everything short of using an actual checksum and so far looks good @laryn 

The clean URL bug of Backdrop/CiviCRM on Lando is holding me back from crafting an actual link (might need to finally try fix it).

**Comment by herbdool** [comment]
I've tested a URL with the checksum and it works. Looks good to me.

BTW, @laryn I usually just preview the civi mailing and it'll generate a checksum in the URL that way as well. Then you don't need to find the mail log.
