### ISSUE TITLE
Fatal MYSQL error on install: REFERENCES command denied to user

### ISSUE THREAD

**Issue by jenlampton** [civicrm/civicrm-backdrop#133]
I am trying to add CiviCRM to an existing Backdrop site. 

I was able to download the module from the CiviCRM website, and enable via the modules page. Then I navigated to `civicrm/setup` and once I resolved the permissions issue with triggers, I attempted to load default content by ticking the box next to `Load sample data`.

As soon as I hit  "Install CiviCRM" I was greeted with the fatal error:
```
Civi\Setup\Exception\SqlException: Cannot execute CREATE TABLE `civicrm_acl_cache` ( `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique table ID', `contact_id` int unsigned COMMENT 'Foreign Key to Contact', `acl_id` int unsigned NOT NULL COMMENT 'Foreign Key to ACL', `modified_date` timestamp NULL COMMENT 'When was this cache entry last modified' , PRIMARY KEY (`id`) , INDEX `index_contact_id`( contact_id ) , INDEX `index_acl_id`( acl_id ) , INDEX `index_modified_date`( modified_date ) , CONSTRAINT FK_civicrm_acl_cache_acl_id FOREIGN KEY (`acl_id`) REFERENCES `civicrm_acl`(`id`) ON DELETE CASCADE ) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC: REFERENCES command denied to user 'backdrop'@'localhost' for table 'civicrm_acl' in Civi\Setup\DbUtil::sourceSQL() (line 204 of backdrop/modules/contrib/civicrm/setup/src/Setup/DbUtil.php). 
```

Now all pages under `/civicrm/` (includin `civicrm/setup`) show the page "CiviCRM Installed" with the message "CiviCRM has been successfully installed" but I don't think it has installed. If it had, I'd be able to see and or use civi in here somewhere, wouldn't I?

**Comment by jenlampton** [comment]
I have attempted to disable and uninstall the CiviCRM module, but when I enable it to start on a fresh install, I still get the "CiviCRM Installed" page, even though I have not yet run the Civi installer. (I did also delete the `civicrm.settings.php` file from the docroot, but that does not seem to help.)

**Comment by jenlampton** [comment]
Hm, I just tried the exact same process all over again, but without ticking the default content option, and I've run into exactly the same error. I suspect the problem might be with the install interface itself. 

I will try the command line installer and see if I can get that working.

**Comment by jenlampton** [comment]
I'm seeing the same `REFERENCES command denied to user` error when attempting to install from the command line using `cv`. 

I've located some documentation that includes all the specific MySQL permissions needed for the CiviCRM tables, turns out it's quite a bit more than was necessary for Drupal or Backdrop:
```
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, TRIGGER, CREATE ROUTINE, ALTER ROUTINE ON civicrm.* TO 'civicrm_user'@'localhost' IDENTIFIED BY 'realpasswordhere';
```

The CiviCRM installer specifically checked for the `TRIGGER` command before allowing the installer to begin, I wonder if it might be possible to check for the other permissions that are specific to Civi to prevent this from happening to other people who are adding Civi to an existing site?

**Comment by herbdool** [comment]
@jenlampton can you report this to the main civicrm project https://lab.civicrm.org/explore/groups? This doesn't seem to be specific to the civicrm_backdrop code which is just a small part of the core package - just to help integrate CiviCRM and Backdrop.
