### ISSUE TITLE
Feature request: Layout access conditions that consider query parameters

### ISSUE THREAD

**Issue by bugfolder** [civicrm/civicrm-backdrop#135]
[A recent forum post](https://forum.backdropcms.org/forum/how-configure-layout-civicrm-pages) asked for a way to put a donation block on a single CiviCRM event page. This is an example of a broader need, of being able to customize specific CiviCRM pages with layouts and blocks. Elsewhere in Backdrop, we could use a _URL path_ visibility condition for that, but since CiviCRM uses query parameters to distinguish pages and the URL path visibility condition doesn't consider query parameters part of the URL path, the URL path visibility condition won't work for that. So there is a need for a visibility condition that considers query parameters.

PR to follow.

**Comment by bugfolder** [comment]
Some further explanation (originally intended for a README file).

CiviCRM handles URLs differently from the rest of Backdrop in two ways, which can be illustrated by a typical CiviCRM URL, for example, an event page:

```
http://example.com/civicrm/event/info?id=1&rest=1
```

1. CiviCRM distinguishes between different pages by using _query parameters_, which are given by everything that comes after the `?` in this URL.
2. Backdrop paths typically include multiple words separated by `/`. While it looks like the Backdrop path for this URL would be `civicrm/event/info`, the _system path_ (used internally in Backdrop) for all CiviCRM pages is just `civicrm`.

This behavior complicates the problem of creating layout and block visibility conditions for CiviCRM pages in Backdrop.

When creating an alternative layout for a CiviCRM page, the layout must have the path `civicrm` (nothing more) to be considered for any CiviCRM page. But then it will be considered for _every_ CiviCRM page. You can limit it to particular classes of page by using visibility conditions on the layout (or limit its blocks by using visibility conditions on the blocks).

To limit a layout or block to particular classes of page—for example, all event information pages—you can use a _URL path_ visibility condition. To have a layout or block appear on all event information pages, you would use a URL path visibility condition with a path of `civicrm/event/info`. (Note, though, that the path for the layout is still just `civicrm`.)

You may, however, wish to make the visibility condition even more fine-grained: limiting a layout or block to a _specific_ event (or contribution form, or other CiviCRM entity). In this case, the visibility condition needs to take into account the _query parameters_ —the information that comes after the `?`. An ordinary URL path visibility condition won't work for that: this is where the visibility condition provided by this module, the _CiviCRM URLs_ visibility condition, comes in.

You can create one or more CiviCRM URLs as visibility conditions, which can contain both path text (to the left of the `?`) and query parameters (to the right of the `?`). You can define any number of possible matches for a given layout, one per line. If any one line matches the page URL, the layout will be used. The matching rules are:

* The path text must match _exactly_;
* All of the query parameters in the visibility condition must be present and equal in value to the query parameters in the page URL.
* Query parameter order is irrelevant; `id=2&reset=1` behaves the same as `reset=1&id=2`.
* Extra query parameters in the page URL are ignored. 

Most of the time you don't need to include `reset=1`. For event info and registration pages, typically only the `id=...` parameter is needed.

So, for example, to use a layout on the event information and event registration pages for an event with event ID 2, you would use these values for the CiviCRM URL visibility condition:

```
civicrm/event/info?id=2
civicrm/event/register?id=2
```

**Comment by laryn** [comment]
This is awesome @bugfolder! 

Custom layouts for a particular contribution page/campaign, or a particular event -- amazing possibilities!

I'll try to test when I get a chance... (I know I say that a lot 😖)

**Comment by stpaultim** [comment]
We (Triplo) finally got a chance to test this on the site where this issue originally came up. It seems to be working great. Thanks!

@bugfolder - Is this CiviCRM Checksum supposed to be here?

![civi-patch](https://user-images.githubusercontent.com/3144571/123202460-42fe6900-d47a-11eb-9e38-5cc6432b07c4.png)

**Comment by bugfolder** [comment]
@stpaultim, I don't know about the "CiviCRM checksum" — that was already part of the module before I got there and I'm not sure how it would be used. (Perhaps @laryn can say more?)

**Comment by laryn** [comment]
That's separate functionality, see here for the background: 

 - https://github.com/civicrm/civicrm-backdrop/issues/124

Basically it allows you to adjust visibility on a block based on whether someone is coming through a specialized ("checksum") link from CiviMail.

**Comment by laryn** [comment]
I left one minor comment on the code, and did some basic testing -- seems to work as advertised! Thumbs up from me.

**Comment by herbdool** [comment]
I've added some comments.

Additionally, I'm thinking that we might need a way to explain to people how to have multiple layouts for CiviCRM and when to use what. First off, maybe we should consolidate the "CiviCRM pages" visibility condition into the main module from the `civicrmtheme` module. People might want to use it even if they're not using the theme module.

And we should add to the docs how to use Layouts with CiviCRM. It's not intuitive that the path should be just `civicrm` and then use visibility conditions for different components. What happens if CiviCRM pages and CiviCRM URLs are used together?

**Comment by bugfolder** [comment]
Agreed that we should move "CiviCRM pages" condition into the main module, and agreed for the need to expand the CiviCRM docs on how to use layouts. Seems that both of those are follow-up tasks. Maybe moving "CiviCRM pages" (and updating its description per comments in this PR) should be a new issue with its own PR.

**Comment by laryn** [comment]
I've attempted to move this issue over to Gitlab:

 - https://lab.civicrm.org/dev/backdrop/-/issues/7

**Comment by herbdool** [comment]
Thanks @bugfolder! Merged.
