### ISSUE TITLE
Use lab.civicrm.org for tracking issues instead of github

### ISSUE THREAD

**Issue by herbdool** [civicrm/civicrm-backdrop#149]
Please create your issues here instead: https://lab.civicrm.org/dev/backdrop/-/issues.

We'd like to use the CiviCRM standard for issue tracking.

**Comment by laryn** [comment]
@herbdool Do we need to transfer all of the existing issues from here to there?

**Comment by herbdool** [comment]
Probably, but there doesn't seem to be any easy way to do that.

**Comment by laryn** [comment]
I can start moving some of the easy ones over one by one via copy/paste. You may need to close them here when moved over.

**Comment by bugfolder** [comment]
Should PRs be made against this code repo and then linked to the GL issue? Or something else?

**Comment by herbdool** [comment]
You are correct @bugfolder. Make the PR here and link to the GL issue.

**Comment by jenlampton** [comment]
I've seen this issue, but I don't have any way to create issues on https://lab.civicrm.org/dev/backdrop/-/issues (I'm unable to log in with my civi credentials, and am not getting a password reset email). 

I'm going to create my issue here since I'm seeing it now and can write it up well, but apologize in advance for any additional copy/paste work I make for myself (or more importantly, anyone else!) in the future.

**Comment by mlutfy** [comment]
@jenlampton The email we have on your user record of civicrm.org seems to be an expired domain? jeneration dot com.

I double-checked the password reset and it seems OK. Although the login form was pretty horrible (reset link at the top), so I fixed that.

I'll migrate the issues to Gitlab in a min.

**Comment by jenlampton** [comment]
Thanks @mlutfy! The password reset form showed me a message as though the email address I provided (my current one) was correct. When that it is not the case, there should be an error message (not a success message) letting people know that they are NOT getting a password reset email. When it says I AM getting an email, and then I don't, the system just seems broken.

**Comment by mlutfy** [comment]
@jenlampton I had done a few reset attempts, before and after updating your email. The rest is standard Drupal9, which is very cringe by default. I don't know much about Drupal, but if there are module or something I can enable, happy to do that.

ps: having delays with the issue import, will do later

**Comment by mlutfy** [comment]
Moved: https://lab.civicrm.org/dev/backdrop/-/issues/71
