### ISSUE TITLE
Status of CiviCRM for Backdrop?

### ISSUE THREAD

**Issue by jackaponte** [civicrm/civicrm-backdrop#19]
Hi all! Any news on the current status of CiviCRM for Backdrop or a likely timeline for a stable release? At Palante we're building a couple of Backdrop sites which will need CiviCRM integration. They're likely to launch within the next few months, so we're eager to hear where things are at and find out if there's anything we can help with in the efforts to get official Backdrop support in Civi.

Tagging folks involved in [the most recent active issue here in GitHub:](https://github.com/civicrm/civicrm-backdrop/issues/16), hope you don't mind! @klonos @PalanteJon @totten @nganivet @herbdool

**Comment by jackaponte** [comment]
Also tagging @jenlampton and @quicksketch even though they weren't involved in that aforementioned conversation! :)

**Comment by herbdool** [comment]
I figured it was ready for an "alpha" release. @palantejon in issue #16 mentions CRM-29011 (which no longer seems to exist in the Civi issue queue). Basic documention exists: https://wiki.civicrm.org/confluence/display/CRMDOC/Installing+CiviCRM+for+Backdrop+CMS So I don't know of anything else really preventing an official release (other than coordinating with the main CiviCRM core maintainers to build a Backdrop release). Would be nice to get #15 fixed but not a deal breaker.

**Comment by jackaponte** [comment]
@herbdool, just checked and Jon mentioned [CRM-19011](https://issues.civicrm.org/jira/browse/CRM-19011), just one digit off. :)

Issue #15 (admin layout not used for Civi pages) is fairly significant for us, we're finding in our site builds, but also not a total deal-breaker.

Do folks know of anything else preventing an official release, besides coordination with CiviCRM core maintainers? Tagging a few core maintainers here in the interest of advancing the conversation: @kurund @totten @colemanw

**Comment by herbdool** [comment]
So I've got a working solution to #15 in a PR for this project.

As for CRM-19011 I was able to replicate the bug. It's not clear if it's a bug with the core or with this repository. I'm guessing this one so I'm going to create an issue for it here as well.

Other than that I don't think there are any deal-breakers.

**Comment by jackaponte** [comment]
Thanks for the update, @herbdool! I've got it on my todo list to test your solution in #15 and will hopefully get to do so soon. I'm not sure who has write access to bring your pull request in if it works, though.

Thanks also for creating issue #22!

Tagging a bunch of CiviCRM and Backdrop folks again to figure out how to make the final push needed for an official CiviCRM release for Backdrop! @jenlampton @quicksketch @totten @kurund @colemanw

**Comment by mikerockett** [comment]
I'm unable to install Civi on Backdrop (1.7)

> The info file (temporary://update-extraction-c6765b48/civicrm-backdrop-1.x-4.7.19/modules/civicrm_member_roles/civicrm_member_roles.info) does not define a 'type' attribute.

Using https://github.com/civicrm/civicrm-backdrop/archive/1.x-4.7.19.tar.gz as an install URL - is that the correct URL to use?

**Comment by herbdool** [comment]
@mikerockett you shouldn't have to install the modules separately. Download and install the whole CiviCRM project for Backdrop here https://civicrm.org/download/list and put into /modules.

**Comment by mikerockett** [comment]
@herbdool That was what I tried first, but it throws this error:

> This installer can only be used for the Drupal version of CiviCRM.

**Comment by herbdool** [comment]
@mikerockett Right, that's what it says in the initial documentation too https://wiki.civicrm.org/confluence/display/CRMDOC/Installing+CiviCRM+for+Backdrop

Just to check I'm also trying the install on Pantheon and see that error. I'm not sure if it's a Backdrop issue. Those functions are used for all CMSes.

**Comment by herbdool** [comment]
Once I fill in the database credentials on the install page the mysqli error disappears.

CiviCRM installs alright, but when it redirects to the install.php page it gives a fatal error:

`Fatal error: Call to undefined function config() in /srv/bindings/9a08664a0cea4cbe89fb711d7e63e7c9/code/core/includes/bootstrap.inc on line 2126`

When I manually enable the civicrm module it all looks fine. So just need to track down the config() error could be with the way CiviCRM is bootstrapping Backdrop.

**Comment by mikerockett** [comment]
@herbdool - You are right, I do apologise. I'd initially briefly read the documentation, but missed out on it for some reason... My bad.

Will try again in a few hours and let you know how it goes.

Anyways, could this process be made a little smoother? Will Civi ever be added to the Backdrop projects/modules directory?

**Comment by herbdool** [comment]
@mikerockett I think the feedback is helpful so no apologies required. Feel free to make an issue for each separate fix/improvement. It'll make it easier to track what needs to be done and then this thread can be closed.

For sure this can be made smoother. To add it to the Backdrop projects installer would require Backdrop allowing third-party installs. I think it would be difficult to do it with Civi since it's a hybrid library/module under Drupal and Backdrop.

**Comment by mikerockett** [comment]
@herbdool - perfect, I will do so.

**Comment by mikerockett** [comment]
@herbdool Okay, so I did as it said, and filled out the credentials. It installed fine, but I then got this error, as opposed to the one you got:

> **Fatal error:** Uncaught Error: Call to undefined function config_get() in \core\includes\theme.maintenance.inc:50
Stack trace:
0 \core\includes\bootstrap.inc(3171): _backdrop_maintenance_theme()
1 \core\includes\errors.inc(186): backdrop_maintenance_theme()
2 \core\includes\bootstrap.inc(2838): _backdrop_log_error(Array, true)
3 [internal function]: _backdrop_exception_handler(Object(Error))
4 {main} thrown in \core\includes\theme.maintenance.inc on line 50

This may have been because I was logged out, but it worked nonetheless. Seems to be running now.

**Comment by herbdool** [comment]
@jackaponte can you close this issue?

Regarding the last comment, undefined function config_get(), I've created a core issue: https://issues.civicrm.org/jira/browse/CRM-20612

**Comment by jackaponte** [comment]
Thanks for closing this ticket, @colemanw! This is all very exciting, thank you so much who worked to get CiviCRM for Backdrop released! <3
