### ISSUE TITLE
CiviCRM-related warning when saving Backdrop permissions page

### ISSUE THREAD

**Issue by jackaponte** [civicrm/civicrm-backdrop#23]
With CiviCRM 4.7.18 and Backdrop 1.6.3, I see many instances of this warning message when saving the Backdrop permissions page, probably one warning per permission:

`Warning: in_array() expects parameter 2 to be array, null given in civicrm_user_admin_permissions_submit() (line 1044 of /var/www/test/alp/modules/civicrm/backdrop/civicrm.module).`

Nothing seems to go awry, but it's certainly noisy, whether messages are displayed on screen or only in the Backdrop logs!

Has anyone else noticed this?

**Comment by jackaponte** [comment]
I also see one set of these notices and warnings upon saving the Permissions page:

```
Notice: Undefined index: role_names in civicrm_user_admin_permissions_submit() (line 1032 of /var/www/test/alp/modules/civicrm/backdrop/civicrm.module).
Warning: array_search() expects parameter 2 to be array, null given in civicrm_user_admin_permissions_submit() (line 1032 of /var/www/test/alp/modules/civicrm/backdrop/civicrm.module).
Notice: Undefined index: in civicrm_user_admin_permissions_submit() (line 1038 of /var/www/test/alp/modules/civicrm/backdrop/civicrm.module).
Warning: array_filter() expects parameter 1 to be array, null given in civicrm_user_admin_permissions_submit() (line 1038 of /var/www/test/alp/modules/civicrm/backdrop/civicrm.module).
Warning: array_intersect(): Argument #1 is not an array in CRM_Core_Permission::validateForPermissionWarnings() (line 673 of /var/www/test/alp/modules/civicrm/CRM/Core/Permission.php).
```

Those messages actually appear before the long string of warnings in my original post.

**Comment by herbdool** [comment]
Fixed
