### ISSUE TITLE
Add maintainer request

### ISSUE THREAD

**Issue by herbdool** [civicrm/civicrm-backdrop#34]
Would you be willing to add me as a maintainer? Currently there doesn't seem to be anyone who has capacity to merge bug fixes and other PRs.

@colemanw @totten @jenlampton

**Comment by jenlampton** [comment]
I would love to add you as a maintainer @herbdool.  I'm not sure what the official procedures are, if any, so I'm going to do it here via github. @colemanw @totten let me know if there is another way new maintainers should be managed.

**Comment by jenlampton** [comment]
@herbdool it looks like I don't have access to collaborator settings for this project, so we'll need to delegate to @colemanw and @totten.

**Comment by colemanw** [comment]
Done.

**Comment by jenlampton** [comment]
Thank you!
