### ISSUE TITLE
Get installer working

### ISSUE THREAD

**Issue by herbdool** [civicrm/civicrm-backdrop#5]
This is probably better as an issue on civicrm-core but want to keep track of this. in civicrm-core > install/index.php there's a lot of checking for Drupal, Wordpress, Joomla. Either we get the installer checking for Backdrop or we see if we can fool it into thinking Backdrop is Drupal and see if it installs. The first option is better.

**Comment by quicksketch** [comment]
Agreed, long-term we'll need to treat Backdrop differently from Drupal as both projects continue to change. The more direct support we have for Backdrop the better.

**Comment by quicksketch** [comment]
Here's the core issue where @herbdool is working: https://github.com/civicrm/civicrm-core/pull/8177

That is currently held up by a core issue that affects the CiviCRM installer: https://github.com/backdrop/backdrop-issues/issues/1834, which we can fix in the immediate future.
