### ISSUE TITLE
Shoreditch theming

### ISSUE THREAD

**Issue by laryn** [civicrm/civicrm-backdrop#51]
There will probably be some more areas where Shoreditch theming will need some Backdrop-specific tweaks when Shoreditch is officially released. Maybe we can collect them here. One I've noticed is the status messages:

![backdrop-shoreditch](https://user-images.githubusercontent.com/871421/39591141-74707cfc-4ec8-11e8-893e-21c3cac77714.png)

**Comment by laryn** [comment]
Might as well link this here as well:
 - https://github.com/civicrm/org.civicrm.shoreditch/issues/339 - Performance issues due to Shoreditch CSS

**Comment by herbdool** [comment]
That performance issue sucks. I haven't tried Shoreditch on production yet - do you know if the same issue exists in Drupal?

**Comment by laryn** [comment]
I believe so but will have to test further to be sure. I'll update that ticket when I do.

**Comment by laryn** [comment]
@herbdool Yes, looks like a Drupal issue as well, and not just Shoreditch related. I am not 100% sure I follow but it looks like maybe the Drupal module will be updated, which could then be moved into the Backdrop module as well.

See:
 - https://github.com/civicrm/civicrm-core/pull/12872
 - https://lab.civicrm.org/dev/core/issues/378
 - https://github.com/civicrm/civicrm-core/pull/12929

**Comment by herbdool** [comment]
I can see how those issues are relevant but I couldn't find reference to performance. Did I miss it?

I would hope that even if Shoreditch is loading that it wouldn't kill performance. Hopefully it gets cached with rest of CSS

**Comment by laryn** [comment]
@herbdool I think the performance issue in relation to the mobile page speed was almost exclusively due to the Shoreditch CSS file, which is huge and gets loaded on every page whether needed or not. It does not seem to get cached with the other CSS.

**Comment by laryn** [comment]
Closing as outdated. New issue: https://lab.civicrm.org/dev/backdrop/-/issues/9
