### ISSUE TITLE
Show CiviCRM status in Backdrop status report?

### ISSUE THREAD

**Issue by laryn** [civicrm/civicrm-backdrop#62]
@herbdool I think it would be a good idea to pull in the CiviCRM version in the Backdrop status report (including a red warning button if there's a security release/warning active in CiviCRM). What do you think of the idea?

![screen shot 2019-02-21 at 10 06 35 am](https://user-images.githubusercontent.com/871421/53183168-6ec66700-35c0-11e9-9f9f-6ef6eb84d3bd.jpg)

**Comment by laryn** [comment]
I should add, if you agree I can try to pull it together!

**Comment by herbdool** [comment]
Great idea!

**Comment by laryn** [comment]
See what you think @herbdool.

Critical message:
![screen shot 2019-02-22 at 1 02 00 am](https://user-images.githubusercontent.com/871421/53225564-1d5cbd00-363e-11e9-8c39-2fc5fa46202e.jpg)

Otherwise:
![screen shot 2019-02-22 at 1 05 39 am](https://user-images.githubusercontent.com/871421/53225574-251c6180-363e-11e9-9c78-6a28f76dce42.jpg)

PR: https://github.com/civicrm/civicrm-backdrop/pull/63

**Comment by herbdool** [comment]
I think it looks great! Drupal 7 sites might also like this PR.

There are some small syntax warnings that need to be fixed before merging. Check Jenkins report

**Comment by laryn** [comment]
@herbdool Okay, will try to clean up this one (and my other PR most likely). I'll submit a similar PR for the Drupal module.

**Comment by herbdool** [comment]
RTBC.
