### ISSUE TITLE
Exposed contact 'created date' in a view has no formatting options

### ISSUE THREAD

**Issue by laryn** [civicrm/civicrm-backdrop#68]
Without adding this `created_date` field to `civicrm.core` explicitly (PR coming) I found that the created date could be added to a view, but no date formatting options were available (as they were for the modified date). This matches the functionality for the created date with what is there currently for the modified date.

**Comment by laryn** [comment]
(I also PR'ed the same for Drupal)

**Comment by herbdool** [comment]
Code looks good. I see the commit but no PR yet.

**Comment by laryn** [comment]
Oops!

**Comment by herbdool** [comment]
Thanks @laryn!
