### ISSUE TITLE
Installing CiviCRM via drush does not set permissions

### ISSUE THREAD

**Issue by tabroughton** [civicrm/civicrm-backdrop#89]
When installing civicrm in backdrop manually permissions are set as part of the process - this is not present in the drush install command.  

This is because the code to update the permissions is within a function `civicrm_install_set_backdrop_perms() ` which is in the user facing index.php of the install scripts in civicrm-core.  Incidently this code would have been better placed elsewhere.

There is no code for the drush script to call nor is it included in the script itself and so no permissions are set.

-------
PR https://github.com/civicrm/civicrm-backdrop/pull/93

**Comment by tabroughton** [comment]
Have created a PR for this issue.

**Comment by herbdool** [comment]
Thanks @tabroughton
