### ISSUE TITLE
Convert use of hook_user_* to the new signature

### ISSUE THREAD

**Issue by herbdool** [civicrm/civicrm-backdrop#9]
Instead of `function civicrm_user_update(&$edit, &$user, $category) {`

it should now be:

`hook_user_update($account)`

a per https://api.backdropcms.org/api/backdrop/core%21modules%21user%21user.api.php/function/hook_user_update/1

**Comment by quicksketch** [comment]
Also fixed in https://github.com/civicrm/civicrm-backdrop/pull/12. Thanks @herbdool!
